import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import homeIcon from "@/../public/home-icon.png";
import historyIcon from "@/../public/history-icon.png";
import NavigationLink from "./components/NavigationLink";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div className="absolute flex gap-4 left-4 top-4">
          <NavigationLink href="/" src={homeIcon} alt="Home" />
          <NavigationLink href="/comparisons" src={historyIcon} alt="History" />
        </div>

        {children}
      </body>
    </html>
  );
}
